### ISSUE TITLE
Availability for return value (dump)

### ISSUE THREAD

**Issue by artemirq** [ziishaned/dumper.js#17]
Like this

```js
console.log(`My dump value is: ${dump(variable, { return: true })}`);
```

**Comment by bonesoul** [comment]
+1

**Comment by AntonTrofimenkoMobiDev** [comment]
> Like this
> 
> ```js
> console.log(`My dump value is: ${dump(variable, { return: true })}`);
> ```

This library is not intended entirely for this. There is a small workaround, but I still advise you to use some other library.

```javascript
import Dumper from 'dumper.js/src/dumper';
function dumpToString(variable) {
  return (new Dumper()).generateDump(variable);
}
const someObject = { a: 1, b: true };
const printableString = dumpToString(someObject);
```

**Comment by artemirq** [comment]
@AntonTrofimenkoMobiDev This issue currently is not actual for me. So, you proposed good solution, I close issue. Nice, thanks
